title: Cube2D Engine
description: A 2D game engine which uses wren as its scripting language
theme: just-the-docs

url: https://mastercuber55.github.io/Cube2D
favicon_ico: "/Assets/Images/favicon.ico"

aux_links:
  "raylib":
    - "https://raylib.com"
  "wren":
    - "https://wren.io"
  "Cube2D Engine on GitHub":
    - "https://github.com/mastercuber55/Cube2D-Engine"

aux_links_new_tab: false

footer_content: "Made with &hearts by Cube Nerd | Copyright &copy; 2023-2023 Cube Nerd. Distributed by an <a href=\"https://github.com/mastercuber55/Cube2D-Engine/blob/main/LICENSE.txt\">MIT license.</a>"